### ISSUE TITLE
error while building hello file from Getting Set Up

### ISSUE THREAD

**Issue by mateus-md** [VoltLang/Volta#62]
# system:
OS: Pop 22.04 jammy
kernel version: 5.19.0-76051900-generic

# problem:
after fallowing [this guide](http://docs.volt-lang.org/doc/tvpl/c2-setup.html) I can't finish the last step (``battery build``) because of the fallowing outputs:
```
[redacted]/Volta/src/volt/visitor/prettyprinter.d(73): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
[...]
[redacted]/Volta/lib/src/volta/parser/templates.d(244): Error: `opSub` is obsolete.  Use `opBinary(string op)(...) if (op == "-")` instead.
```
and other similar deprecation errors that may be irrelevant.
the error persists building from ``hello/``, root, using ``battery.txt`` or an equivalent ``battery.toml`` (I also received an error of a missing toml file in the hello folder)

I have all dependencies installed and updated to latest versions, including battery. I cloned all repos today from main branch. any help would be great.

**Comment by Wallbraker** [comment]
@mateus-md Hello, thank you for your report, and apologies for the late reply. I have fixed this particular issue. Looks like some things got deprecated in D and I hadn't built with a new enough version of `DMD`/`GDC`. I was able to compile with `LLVM-14.0.6` and `GDC-12`.

Please try again after updating Volta. If this issue persists then re-open this issue, I'll take a look no worries at all. If you run into other issues please open a new issue. Thank you again!
